llm_backend: openai
embedding_backend: openai
model_name: gpt-3.5-turbo
embedding_model_name: sentence-transformers/all-MiniLM-L6-v2
repo_id: gpt2
repositories:
  owner/repo1:
    start_issue_number: 100
    branch: main
    recent_period:
      months: 1
    enable_discussion_reply: true
    start_discussion_number: 1
  owner/repo2:
    start_issue_number: 200
    branch: develop
    recent_period:
      weeks: 2

check_interval: 300
device: -1
github_base_url: https://api.github.com
openai_api_base: https://api.openai.com/v1
huggingface_api_base: null

prompt_template: |
  You are a smart assistant capable of answering user questions based on provided documents.

  **Rules for answering:**
  1. Always reply in the **same language as the Question**. The language of the Question determines the language of your Answer.
  2. **Ignore the language of the provided documents** when choosing the language for your response. The documents are only for reference, not for language selection.
  3. Provide a detailed answer based on the provided documents and ensure your response is relevant to the Question.
  4. Reference related Issues or Discussions and provide links **only if they are directly relevant**.

  ---

  **Here is the user's Question:**
  {input}

  **Here are some potentially useful documents:**
  {context}

  **Your Answer:**

signature: "\n\n---\n*Response generated by 🤖 [feifei-bot](https://github.com/GreatV/feifei) | {model_name}*"
